"""empty message

Revision ID: 6cab9a3e1ab7
Revises: 
Create Date: 2024-10-21 13:27:25.414338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cab9a3e1ab7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('comment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('favorite_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('flavor_preference', schema=None) as batch_op:
        batch_op.drop_constraint('flavor_preference_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('flavor_preference_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'flavor', ['flavor_id'], ['id'])

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('big_type', sa.String(length=100), nullable=True))

    with op.batch_alter_table('food_flavor_association', schema=None) as batch_op:
        batch_op.drop_constraint('food_flavor_association_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('food_flavor_association_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'flavor', ['flavor_id'], ['id'])
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'])

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint('rating_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('rating_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('rating_ibfk_2', 'user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('rating_ibfk_1', 'food', ['food_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('food_flavor_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('food_flavor_association_ibfk_2', 'food', ['food_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('food_flavor_association_ibfk_1', 'flavor', ['flavor_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_column('big_type')

    with op.batch_alter_table('flavor_preference', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('flavor_preference_ibfk_1', 'flavor', ['flavor_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('flavor_preference_ibfk_2', 'user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_ibfk_2', 'user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('favorite_ibfk_1', 'food', ['food_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_ibfk_1', 'food', ['food_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('comment_ibfk_2', 'user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    # ### end Alembic commands ###
